### ISSUE TITLE
A机构对B机构授权之后，A机构授权列表中没有显示出被授权的机构名称

### ISSUE THREAD

**Issue by 253322817** [Sagwed/ehealth-manager#105]
![Uploading 机构授权.png…]()

**Comment by 253322817** [comment]
是被遮挡住了

**Comment by Sagwed** [comment]
![y0 ng zev _zpx 8cv54rgx](https://cloud.githubusercontent.com/assets/9797856/9347312/9e9edc7c-465a-11e5-91f1-48246a206639.png)
