### ISSUE TITLE
查询的机构问题

### ISSUE THREAD

**Issue by slRain** [Sagwed/ehealth-manager#54]
所有的查询，运营公司的用户才能选择所有机构和全部机构，非运营公司的管理员只能选择所管权限下的某一个机构

**Comment by slRain** [comment]
暂时修改为 options： $root.manageOrganizations ，存在分页查询的问题。

**Comment by slRain** [comment]
4个查询页面中，机构的选择修改为：当用户为的管理单元为"eh"的时候可以选择”所有机构“，否则为必选项。

**Comment by Sagwed** [comment]
如果同时存在申请机构和目标机构的查询，不完全是必选，而是2个机构不能同时选中所有机构，换句话就是只要2个中有一个选择了机构即可通过校验。

**Comment by slRain** [comment]
已修改
