### ISSUE TITLE
关于机构选择器中机构获取数量的问题。

### ISSUE THREAD

**Issue by slRain** [Sagwed/ehealth-manager#56]
在查看 organization-selector.js的时候发现，findOrgansByManageUnit服务是根据管理单元获取所能管理的机构是分页查询，我不知道这个分页返回的是不是10条。如果是10条，那么机构选择器里面的机构数量应该是不正确的。

**Comment by Sagwed** [comment]
是10条 我会给机构选择器增加更多功能

**Comment by Sagwed** [comment]
已修改
