### ISSUE TITLE
关于机构被删除后，机构管理员的处理方式的疑问。

### ISSUE THREAD

**Issue by slRain** [Sagwed/ehealth-manager#57]
使用15068720778账号，登录进去后，发现该机构已经被删除。
疑问：已经被删除或注销的机构，其机构管理员怎么处理？

**Comment by Sagwed** [comment]
该机构并未删除，而是 manageUnit 字段被修改。
正常情况应该是服务端在更改机构 manageUnit 时同时更改对应的管理员账号 manageUnit 字段。
出现这种情况现在只能在登录时严格判断，拒绝该用户登录。
