### ISSUE TITLE
新建机构，新建信息不是很规范的填写，然后提交保存信息，报错（servererror）

### ISSUE THREAD

**Issue by 253322817** [Sagwed/ehealth-manager#60]
![default](https://cloud.githubusercontent.com/assets/12932907/8795708/bcde09e2-2fc1-11e5-83f1-2bd9e0ca3b7f.jpg)

**Comment by Sagwed** [comment]
对各个输入字段做了长度校验

**Comment by 253322817** [comment]
验证已解决
