### ISSUE TITLE
纳里运营平台，登陆时用户名应自动过滤掉空格，现在纳里运营平台退出后再使用其他用户登陆，用户名后会自动增加一个空格，有空格时登陆提示密码错误

### ISSUE THREAD

**Issue by 253322817** [Sagwed/ehealth-manager#63]
![1](https://cloud.githubusercontent.com/assets/12932907/8795887/4a01224a-2fc3-11e5-9007-244c8f27387d.png)

**Comment by Sagwed** [comment]
登录时考虑自动去除用户名前后空格。

**Comment by 253322817** [comment]
验证已解决
