### ISSUE TITLE
机构-新增管理员账号,点击新增账号,右侧头像上传功能未显示,新增成功后才显示头像上传功能

### ISSUE THREAD

**Issue by 253322817** [Sagwed/ehealth-manager#70]
机构-新增管理员账号,点击新增账号,右侧头像上传功能未显示,新增账号后才显示头像上传功能,选择后需要确定修改才上传头像成功

**Comment by Sagwed** [comment]
图像都是要新增记录后才能上传的

**Comment by 253322817** [comment]
与开发沟通，现在运营平台的逻辑是先有数据，然后在有图片，图片衣服与机构
