### ISSUE TITLE
机构---新建机构，机构类型、机构等级、行政归属选择值后，展示宽度变窄

### ISSUE THREAD

**Issue by 253322817** [Sagwed/ehealth-manager#71]
![1](https://cloud.githubusercontent.com/assets/12932907/8820082/efcdc2de-3084-11e5-8039-b5573a6f9ed9.png)

**Comment by Sagwed** [comment]
用的什么浏览器？

**Comment by Sagwed** [comment]
浏览器缩放造成了下拉列表框高度变小，而字体并未随之变小。
由于缩放成多高完全是谷歌浏览器控制的，暂时不能解决此问题。
应避免缩放屏幕。

**Comment by 253322817** [comment]
同意开发意见
