### ISSUE TITLE
医生---新建医生，建议医生头像、职称照片、执业证书照片可以和医生信息一起保存

### ISSUE THREAD

**Issue by 253322817** [Sagwed/ehealth-manager#73]
![33](https://cloud.githubusercontent.com/assets/12932907/8820401/a7b2dd10-3087-11e5-88c4-130232ff3d5a.png)

**Comment by Sagwed** [comment]
服务端不支持，必须先有记录才能上传文件

**Comment by 253322817** [comment]
暂时可以不改，还是建议后期有可能的话进行优化
