### ISSUE TITLE
业务查询-查询结果只有10条记录,全部显示在第一页,但能翻页到第二页,且无内容

### ISSUE THREAD

**Issue by 253322817** [Sagwed/ehealth-manager#80]
业务查询-查询结果只有10条记录,全部显示在第一页,但能翻页到第二页,且无内容

**Comment by Sagwed** [comment]
涉及到分页的问题
因为服务器没有返回总数或者总页数，所以当 当前页返回10条数据时并不知道还有更多数据
我们只能假设有下一页，但是下一页可能并没有数据

**Comment by slRain** [comment]
如果预先加载下一页，可以避免这个问题，但改动比较大。

**Comment by 253322817** [comment]
验证未解决，与开发沟通此问题暂时不解决，后期再改

**Comment by Sagwed** [comment]
通过总记录条数计算解决
