### ISSUE TITLE
机构---新建机构表单，开户银行可输入字符太短了，需要在加长

### ISSUE THREAD

**Issue by 253322817** [Sagwed/ehealth-manager#87]
![23](https://cloud.githubusercontent.com/assets/12932907/8927045/34a1b3d6-3547-11e5-99f5-8572d1aa3904.png)

**Comment by Sagwed** [comment]
无法在客户端修改，数据库设计成6个字符

**Comment by Sagwed** [comment]
开户银行需改为字典由用户下拉选择
